import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scrollContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    padding: 20,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    marginVertical: 10,
    width: '100%',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 5,
  },
   cardMachine: {
    backgroundColor: '#1D1936',
    borderRadius: 10,
    padding: 20,
    marginVertical: 0,
    width: '100%',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 5,
  },
  titleMachine: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#ffffff',
    textAlign: 'center',
  },
  image: {
    width: 150,
    height: 150,
    marginBottom: 1,
    alignSelf: 'center',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#333',
    textAlign: 'center',
  },
  titleinfo: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#333',
    textAlign: 'center',
  },
  modelName: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 5,
    color: '#ffffff',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#1D1936',
    textAlign: 'center',
  },
    cardInfo: {
    backgroundColor: '#ffffff',
    borderRadius: 10,
    padding: 0,
    marginVertical: 0,
    width: '100%',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 5,
  },
  installationDate: {
    fontSize: 14,
    marginBottom: 20,
    color: '#161616',
    textAlign: 'center',
  },
   infocard: {
    fontSize: 16,
    marginBottom: 20,
    color: '#161616',
    textAlign: 'center',
  },
  infoLabel: {
    fontSize: 16,
    color: '#444',
    fontWeight: 'bold',
    marginBottom: 5,
    textAlign: 'left',
  },
  info: {
    fontSize: 16,
    color: '#555',
    marginBottom: 5,
    textAlign: 'left',
  },
  noMaintenance: {
    fontSize: 16,
    color: '#777',
    textAlign: 'center',
  },
  statusMessageContainer: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusMessage: {
    fontSize: 18,
    textAlign: 'center',
    marginVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: '#FFF',
    borderRadius: 5,
    padding: 10,
    borderWidth: 1,
    borderColor: '#ddd',
    width: '100%',
  },
  statusIcon: {
    marginBottom: 10,
  },
  icon: {
    marginRight: 8,
  },
  whatsappButton: {
    flexDirection: 'row',
    backgroundColor: '#25D366',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: 15,
  },
  printButton: {
    flexDirection: 'row',
    backgroundColor: '#1D1936',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    marginTop: 15,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    marginLeft: 10,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: 300,
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
  },
  modalButton: {
    backgroundColor: '#1D1936',
    padding: 15,
    borderRadius: 10,
    marginTop: 10,
    width: '100%',
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
  },
  titleGInfo:{
    fontSize: 18,
    fontWeight: 'bold',
    margin: 15,
    color: '#333',
    textAlign: 'center',
  },
  divider: {
  height: 1,
  backgroundColor: '#ccc',
  marginVertical: 8,
  width: '100%',
},

});
